package us.i3u.hermesstudio

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.ui.platform.LocalContext

@OptIn(ExperimentalMaterial3Api::class)
@Composable private fun ParityScaffold(title: String, vm: AppViewModel, content: @Composable ColumnScope.() -> Unit) = Scaffold(topBar = { TopAppBar(title = { Text(title) }, navigationIcon = { IconButton(vm::back) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.action_back)) } }) }) { pad -> Column(Modifier.fillMaxSize().padding(pad).padding(16.dp), verticalArrangement = Arrangement.spacedBy(10.dp), content = content) }

@Composable fun JourneyScreen(state: UiState, vm: AppViewModel) = ParityScaffold(stringResource(R.string.journey_title), vm) { val graph = state.journey; val usage = state.skillUsage; Text("${graph?.profile.orEmpty()} · ${graph?.nodes?.size ?: 0} nodes · ${graph?.edges?.size ?: 0} links", fontWeight = FontWeight.Bold); usage?.let { Text("${it.totalActions} actions · ${it.totalLoads} loads · ${it.totalEdits} edits · ${it.distinctSkills} skills") }; LazyColumn(verticalArrangement = Arrangement.spacedBy(8.dp)) { graph?.clusters?.let { items(it) { cluster -> Text("${cluster.first}: ${cluster.second}", style = MaterialTheme.typography.titleSmall) } }; graph?.nodes?.let { items(it, key = { n -> n.id }) { node -> Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(12.dp)) { Text(node.label, fontWeight = FontWeight.Bold); Text("${node.kind} · ${node.category} · ${node.uses}") } } } }; usage?.topSkills?.let { items(it) { skill -> Text("${skill.first}: ${skill.second}") } } } }

@Composable fun WebhooksScreen(state: UiState, vm: AppViewModel) { var edit by remember { mutableStateOf<WebhookEndpoint?>(null) };var add by remember { mutableStateOf(false) }; var name by remember { mutableStateOf("") }; var url by remember { mutableStateOf("") }; if(add||edit!=null) AlertDialog(onDismissRequest={add=false;edit=null}, title={Text(stringResource(R.string.webhooks_add))}, text={Column { OutlinedTextField(name,{name=it},label={Text(stringResource(R.string.name))}); OutlinedTextField(url,{url=it},label={Text("URL")}) }}, confirmButton={TextButton(onClick={val item=edit;add=false;edit=null;if(item==null)vm.createWebhook(name,url) else vm.updateWebhook(item,name,url)}){Text(stringResource(R.string.action_save))}}, dismissButton={TextButton(onClick={add=false;edit=null}){Text(stringResource(R.string.action_cancel))}}); ParityScaffold(stringResource(R.string.webhooks_title),vm) { Row(verticalAlignment=Alignment.CenterVertically){Button(onClick={name="";url="";add=true}){Text(stringResource(R.string.action_add))}; Spacer(Modifier.width(8.dp)); TextButton(onClick=vm::clearWebhookEvents){Text(stringResource(R.string.clear_events))}}; LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){ items(state.webhooks,key={it.id}){hook->Card(Modifier.fillMaxWidth()){Column(Modifier.padding(12.dp)){Text(hook.name,fontWeight=FontWeight.Bold);Text(hook.url);Text("${hook.state} · ✓${hook.delivered} · !${hook.failed}");Row{Switch(hook.enabled,{vm.toggleWebhook(hook)});TextButton(onClick={name=hook.name;url=hook.url;edit=hook}){Text(stringResource(R.string.action_edit))};TextButton(onClick={vm.testWebhook(hook)}){Text(stringResource(R.string.action_test))};TextButton(onClick={vm.deleteWebhook(hook)}){Text(stringResource(R.string.action_delete))}}}}}; if(state.webhookEvents.isNotEmpty()) item{Text(stringResource(R.string.local_events),fontWeight=FontWeight.Bold)}; items(state.webhookEvents){Text(it)} } } }

@Composable fun RuntimeVersionsScreen(state: UiState, vm: AppViewModel) = ParityScaffold(stringResource(R.string.runtime_versions_title),vm) { val versions=state.runtimeVersions; Text("${versions?.platform.orEmpty()} · Runtime ${versions?.activeRuntime.orEmpty()} · WebUI ${versions?.activeWebUi.orEmpty()}",fontWeight=FontWeight.Bold); Button(onClick=vm::restartWebUi){Text(stringResource(R.string.restart_webui))}; LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){ items((versions?.runtime.orEmpty()+versions?.webUi.orEmpty()),key={it.kind+it.version}){v->Card{Row(Modifier.fillMaxWidth().padding(12.dp),verticalAlignment=Alignment.CenterVertically){Text("${v.kind} ${v.version}",Modifier.weight(1f));if(v.active)Text(stringResource(R.string.agent_status_active))else TextButton(onClick={vm.activateVersion(v)}){Text(stringResource(R.string.activate))}}}}; versions?.remoteRuntime?.let{items(it){v->TextButton(onClick={vm.downloadVersion(v,false)}){Text("Download Runtime $v")}}};versions?.remoteWebUi?.let{items(it){v->TextButton(onClick={vm.downloadVersion(v,true)}){Text("Download WebUI $v")}}} } }

@Composable fun AppearanceScreen(state: UiState, vm: AppViewModel) { val source=state.themeSettings; val context=LocalContext.current;val upload=rememberLauncherForActivityResult(ActivityResultContracts.GetContent()){uri->uri?:return@rememberLauncherForActivityResult;val bytes=context.contentResolver.openInputStream(uri)?.use{it.readBytes()}?:return@rememberLauncherForActivityResult;vm.uploadThemeBackground(bytes,uri.lastPathSegment?:"background",context.contentResolver.getType(uri)?:"image/jpeg")};var size by remember(source){mutableStateOf((source?.fontSize?:16).toString())};var text by remember(source){mutableStateOf(source?.textColor.orEmpty())};var accent by remember(source){mutableStateOf(source?.accentColor.orEmpty())};ParityScaffold(stringResource(R.string.appearance_title),vm){OutlinedTextField(size,{size=it.filter(Char::isDigit)},label={Text(stringResource(R.string.font_size))});OutlinedTextField(text,{text=it},label={Text(stringResource(R.string.text_color))});OutlinedTextField(accent,{accent=it},label={Text(stringResource(R.string.accent_color))});Button(onClick={vm.saveTheme(size.toIntOrNull()?:16,text,accent)}){Text(stringResource(R.string.action_save))};TextButton(onClick={upload.launch("image/*")}){Text(stringResource(R.string.upload_background))};if(!source?.backgroundName.isNullOrBlank()){Text(source?.backgroundName.orEmpty());TextButton(onClick=vm::removeThemeBackground){Text(stringResource(R.string.remove_background))}}} }
