package us.i3u.hermesstudio

import android.content.Intent
import android.net.Uri
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun FilesScreen(state: UiState, vm: AppViewModel) {
    val context = LocalContext.current
    var folderDialog by remember { mutableStateOf(false) }
    var manage by remember { mutableStateOf<StudioFile?>(null) }
    if (folderDialog) SimpleNameDialog(stringResource(R.string.files_new_folder), "", { folderDialog = false }) { folderDialog = false; vm.createStudioFolder(it) }
    manage?.let { file -> AlertDialog(onDismissRequest = { manage = null }, title = { Text(file.name) }, text = { Column { TextButton(onClick = { manage = null; vm.openStudioFile(file) }) { Text(stringResource(R.string.files_edit)) }; TextButton(onClick = { context.startActivity(Intent(Intent.ACTION_VIEW, Uri.parse(vm.studioFileUrl(file)))); manage = null }) { Text(stringResource(R.string.files_open_external)) }; TextButton(onClick = { vm.deleteStudioFile(file); manage = null }) { Text(stringResource(R.string.action_delete)) } } }, confirmButton = {}) }
    state.openFile?.let { file -> var content by remember(file.path, state.openFileContent) { mutableStateOf(state.openFileContent) }; AlertDialog(onDismissRequest = vm::closeStudioFile, title = { Text(file.name) }, text = { OutlinedTextField(content, { content = it }, Modifier.fillMaxWidth(), minLines = 12, textStyle = MaterialTheme.typography.bodySmall.copy(fontFamily = FontFamily.Monospace)) }, confirmButton = { TextButton(onClick = { vm.saveStudioFile(content) }) { Text(stringResource(R.string.action_save)) } }, dismissButton = { TextButton(onClick = vm::closeStudioFile) { Text(stringResource(R.string.action_cancel)) } }) }
    Scaffold(topBar = { TopAppBar(title = { Text(stringResource(R.string.files_title)) }, navigationIcon = { IconButton(onClick = { if (state.filesPath.isBlank()) vm.back() else vm.openFiles(state.filesPath.substringBeforeLast('/', "")) }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.action_back)) } }, actions = { IconButton(onClick = { folderDialog = true }) { Icon(Icons.Filled.CreateNewFolder, stringResource(R.string.files_new_folder)) }; IconButton(onClick = { vm.openFiles(state.filesPath) }) { Icon(Icons.Filled.Refresh, stringResource(R.string.action_refresh)) } }) }) { pad -> LazyColumn(Modifier.fillMaxSize().padding(pad), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { item { Text("/" + state.filesPath, fontFamily = FontFamily.Monospace) }; items(state.studioFiles, key = { it.path }) { file -> Card(Modifier.fillMaxWidth().clickable { if (file.directory) vm.openFiles(file.path) else manage = file }, shape = RoundedCornerShape(16.dp)) { Row(Modifier.padding(14.dp), verticalAlignment = Alignment.CenterVertically) { Icon(if (file.directory) Icons.Filled.Folder else Icons.Filled.InsertDriveFile, null); Spacer(Modifier.width(12.dp)); Column(Modifier.weight(1f)) { Text(file.name, fontWeight = FontWeight.Bold); if (!file.directory) Text("${file.size} B", style = MaterialTheme.typography.labelSmall) }; if (!file.directory) IconButton(onClick = { manage = file }) { Icon(Icons.Filled.MoreVert, null) } } } } } }
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun LogsScreen(state: UiState, vm: AppViewModel) { Scaffold(topBar = { TopAppBar(title = { Text(state.openLog?.name ?: stringResource(R.string.logs_title)) }, navigationIcon = { IconButton(onClick = { if (state.openLog != null) vm.closeLog() else vm.back() }) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.action_back)) } }, actions = { IconButton(onClick = { state.openLog?.let(vm::openLog) ?: vm.openLogs() }) { Icon(Icons.Filled.Refresh, stringResource(R.string.action_refresh)) } }) }) { pad -> LazyColumn(Modifier.fillMaxSize().padding(pad), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { if (state.openLog == null) items(state.studioLogs, key = { it.name }) { log -> Card(Modifier.fillMaxWidth().clickable { vm.openLog(log) }) { Column(Modifier.padding(15.dp)) { Text(log.name, fontWeight = FontWeight.Bold); Text("${log.size} · ${log.modified}", style = MaterialTheme.typography.labelSmall) } } } else items(state.logEntries) { entry -> Column { Text("${entry.level} · ${entry.timestamp}", color = if (entry.level.contains("ERROR")) MaterialTheme.colorScheme.error else MaterialTheme.colorScheme.primary, style = MaterialTheme.typography.labelSmall); Text(entry.message, fontFamily = FontFamily.Monospace, style = MaterialTheme.typography.bodySmall); HorizontalDivider() } } } } }

@OptIn(ExperimentalMaterial3Api::class)
@Composable fun ConnectionsScreen(state: UiState, vm: AppViewModel) { Scaffold(topBar = { TopAppBar(title = { Text(stringResource(R.string.connections_title)) }, navigationIcon = { IconButton(vm::back) { Icon(Icons.AutoMirrored.Filled.ArrowBack, stringResource(R.string.action_back)) } }, actions = { IconButton(vm::openConnections) { Icon(Icons.Filled.Refresh, stringResource(R.string.action_refresh)) } }) }) { pad -> LazyColumn(Modifier.fillMaxSize().padding(pad), contentPadding = PaddingValues(16.dp), verticalArrangement = Arrangement.spacedBy(12.dp)) { item { Text(stringResource(R.string.app_relay_title), style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold) }; state.appRelay?.let { relay -> item { Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(16.dp), verticalArrangement = Arrangement.spacedBy(8.dp)) { Text(if (relay.connected) stringResource(R.string.connected) else stringResource(R.string.disconnected)); if (relay.pairingCode.isNotBlank()) Text(relay.pairingCode, style = MaterialTheme.typography.headlineMedium, fontFamily = FontFamily.Monospace); Row { Button(onClick = { if (relay.connected) vm.disconnectRelay() else vm.connectRelay() }) { Text(stringResource(if (relay.connected) R.string.disconnect else R.string.connect)) }; if (relay.connected) TextButton(vm::refreshRelayCode) { Text(stringResource(R.string.refresh_pairing)) } } } } }; item { Text(stringResource(R.string.devices_title), style = MaterialTheme.typography.titleMedium, fontWeight = FontWeight.Bold) }; items(state.studioDevices, key = { it.id }) { device -> Card(Modifier.fillMaxWidth()) { Column(Modifier.padding(15.dp)) { Text(device.name, fontWeight = FontWeight.Bold); Text(device.address); Text("${device.inbound} · ${device.outbound}", style = MaterialTheme.typography.labelSmall); Row { TextButton(onClick = { vm.deviceAction(device, "approve") }) { Text(stringResource(R.string.action_approve)) }; TextButton(onClick = { vm.deviceAction(device, "reject") }) { Text(stringResource(R.string.action_reject)) }; TextButton(onClick = { vm.deviceAction(device, "connect") }) { Text(stringResource(R.string.connect)) } } } } } } } }

@Composable private fun SimpleNameDialog(title: String, initial: String, dismiss: () -> Unit, save: (String) -> Unit) { var value by remember { mutableStateOf(initial) }; AlertDialog(onDismissRequest = dismiss, title = { Text(title) }, text = { OutlinedTextField(value, { value = it }) }, confirmButton = { TextButton(enabled = value.isNotBlank(), onClick = { save(value) }) { Text(stringResource(R.string.action_save)) } }, dismissButton = { TextButton(onClick = dismiss) { Text(stringResource(R.string.action_cancel)) } }) }
